### ISSUE TITLE
Connection not closing even after on_disconnect

### ISSUE THREAD

**Issue by ChaitanyaYeole02** [villekr/ocpp-asgi#16]
Hello @villekr ,
I am facing a problem when the on_disconnect event is called and still my CP is sending messages to our CS. I am thinking of closing the connection manually inside on_disconect

**Comment by ChaitanyaYeole02** [comment]
I received this error, when I connected a lot of CP in only one worker

**Comment by villekr** [comment]
If you think this is a bug in occp_asgi then attach the traceback and example code in order to reproduce the error.

**Comment by villekr** [comment]
Even though it looks like ocpp_asgi/app.py is for some reason sending non-expected ASGI event I can't reproduce the issue. 

In branch https://github.com/villekr/ocpp-asgi/pull/17 I updated the test code so that it's easy to create test Charging Stations and disconnect and connect them freely. But couldn't reproduce this kind of problem.

**Comment by villekr** [comment]
Closing. Please reopen by attaching example code that this issue can be reproduced.
